// GENERATED by scripts/fetch-photos.mjs — do not edit by hand.
//
// CC BY and CC BY-SA oblige us to credit the photographer. `attribution: true`
// means this image may not be shown without its credit rendered somewhere the
// reader can reach, which is what /de/bildnachweis/ is for.

export interface PhotoCredit {
  id: string;
  licence: string;
  licenceUrl: string;
  artist: string;
  page: string;
  attribution: boolean;
  alt: string;
  focus: string;
  aspect: number;
}

export const PHOTO_CREDITS: PhotoCredit[] = [
  {
    "id": "facade-bays",
    "licence": "CC0",
    "licenceUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "artist": "Wilfredor",
    "page": "https://commons.wikimedia.org/wiki/File%3ATorre_Am%C3%A9rica_and_Gran_Meli%C3%A1_Caracas_in_Bello_Monte%2C_Venezuela.jpg",
    "attribution": false,
    "alt": "Hochhausfassade von unten: dieselbe Fensterachse, vielfach wiederholt bis in die Flucht.",
    "focus": "50% 38%",
    "aspect": 1.3535
  },
  {
    "id": "switching-station",
    "licence": "CC BY 2.0",
    "licenceUrl": "https://creativecommons.org/licenses/by/2.0",
    "artist": "seier+seier",
    "page": "https://commons.wikimedia.org/wiki/File%3AHans_chr._hansen%2C_architect-_svanem%C3%B8lle_koblingsstation%2C_copenhagen_1966-1968_(5692115853).jpg",
    "attribution": true,
    "alt": "Betonfassade eines Schaltwerks in strengem Raster, ohne Zierde.",
    "focus": "50% 45%",
    "aspect": 0.8668
  },
  {
    "id": "stair-flights",
    "licence": "CC0",
    "licenceUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "artist": "Jorge Mendoza",
    "page": "https://commons.wikimedia.org/wiki/File%3ASpiral_Staircase%2C_Keck_Center_(U.S._National_Academies).jpg",
    "attribution": false,
    "alt": "Treppenläufe übereinander, von unten gesehen — eine Stufe nach der anderen.",
    "focus": "50% 50%",
    "aspect": 1.5
  }
];

export function photo(id: string): PhotoCredit {
  const found = PHOTO_CREDITS.find((p) => p.id === id);
  if (!found) throw new Error(`Unknown photo id: ${id}`);
  return found;
}
