// GENERATED by scripts/fetch-photos.mjs — do not edit by hand.
//
// CC BY and CC BY-SA oblige us to credit the photographer. `attribution: true`
// means this image may not be shown without its credit rendered somewhere the
// reader can reach, which is what /de/bildnachweis/ is for.

export interface PhotoCredit {
  id: string;
  licence: string;
  licenceUrl: string;
  artist: string;
  page: string;
  attribution: boolean;
  alt: string;
  focus: string;
  aspect: number;
}

export const PHOTO_CREDITS: PhotoCredit[] = [
  {
    "id": "facade-bays",
    "licence": "CC0",
    "licenceUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "artist": "Wilfredor",
    "page": "https://commons.wikimedia.org/wiki/File%3ATorre_Am%C3%A9rica_and_Gran_Meli%C3%A1_Caracas_in_Bello_Monte%2C_Venezuela.jpg",
    "attribution": false,
    "alt": "Hochhausfassade von unten: dieselbe Fensterachse, vielfach wiederholt bis in die Flucht.",
    "focus": "50% 38%",
    "aspect": 1.3535
  },
  {
    "id": "switching-station",
    "licence": "CC BY 2.0",
    "licenceUrl": "https://creativecommons.org/licenses/by/2.0",
    "artist": "seier+seier",
    "page": "https://commons.wikimedia.org/wiki/File%3AHans_chr._hansen%2C_architect-_svanem%C3%B8lle_koblingsstation%2C_copenhagen_1966-1968_(5692115853).jpg",
    "attribution": true,
    "alt": "Betonfassade eines Schaltwerks in strengem Raster, ohne Zierde.",
    "focus": "50% 45%",
    "aspect": 0.8668
  },
  {
    "id": "stair-flights",
    "licence": "CC0",
    "licenceUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "artist": "Jorge Mendoza",
    "page": "https://commons.wikimedia.org/wiki/File%3ASpiral_Staircase%2C_Keck_Center_(U.S._National_Academies).jpg",
    "attribution": false,
    "alt": "Treppenläufe übereinander, von unten gesehen — eine Stufe nach der anderen.",
    "focus": "50% 50%",
    "aspect": 1.5
  },
  {
    "id": "watchmaker",
    "licence": "CC0",
    "licenceUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "artist": "Yılmaz Kilim",
    "page": "https://commons.wikimedia.org/wiki/File%3AWatchmaker_(184539829).jpeg",
    "attribution": false,
    "alt": "Uhrmacher an der Werkbank, über ein Werk gebeugt, Werkzeug in der Hand.",
    "focus": "50% 45%",
    "aspect": 1.7778
  },
  {
    "id": "market-hall",
    "licence": "CC BY 4.0",
    "licenceUrl": "https://creativecommons.org/licenses/by/4.0",
    "artist": "J K Thorne",
    "page": "https://commons.wikimedia.org/wiki/File%3AWoolwich_Public_Market_Hall%2C_Grade_2_Listed_Building._2016-03-05.jpg",
    "attribution": true,
    "alt": "Stahlfachwerk einer Markthalle: viele gleiche Felder, unter einem Dach.",
    "focus": "50% 55%",
    "aspect": 1.3333
  },
  {
    "id": "watch-movement",
    "licence": "CC BY-SA 4.0",
    "licenceUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "artist": "Anil Öztas",
    "page": "https://commons.wikimedia.org/wiki/File%3ANomos_Tangente_neomatik_41_Update%2C_Ref._180%2C_DUW_6101_--_2023_--_0012X.jpg",
    "attribution": true,
    "alt": "Offenes Uhrwerk in Grossaufnahme: Räderwerk, Brücken und Schrauben.",
    "focus": "50% 50%",
    "aspect": 1.5
  },
  {
    "id": "reading-room",
    "licence": "Public domain",
    "licenceUrl": "",
    "artist": "Unknown author",
    "page": "https://commons.wikimedia.org/wiki/File%3AMain_Reading_Room_of_the_New_York_City_Public_Library_on_5th_Avenue_ca%2C_1910-1920.jpg",
    "attribution": false,
    "alt": "Grosser Lesesaal einer Bibliothek, Tischreihen unter hohen Fenstern.",
    "focus": "50% 50%",
    "aspect": 1.2806
  },
  {
    "id": "card-catalogue",
    "licence": "CC BY-SA 4.0",
    "licenceUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "artist": "Fuje23",
    "page": "https://commons.wikimedia.org/wiki/File%3AKansallisarkisto_Helsinki_Rauhankatu_17_luettelohuone_kortistokaappi_2026_02_23.jpg",
    "attribution": true,
    "alt": "Karteikartenschrank im Lesesaal eines Staatsarchivs, Schublade an Schublade.",
    "focus": "50% 50%",
    "aspect": 1.5
  },
  {
    "id": "machine-shop",
    "licence": "Public domain",
    "licenceUrl": "",
    "artist": "Godber, Albert Percy, 1875-1949",
    "page": "https://commons.wikimedia.org/wiki/File%3AInterior_of_the_machine_shop_at_the_Petone_Railway_Workshops%2C_1924_ATLIB_299540.png",
    "attribution": false,
    "alt": "Grosse Maschinenwerkstatt mit Drehbänken in langer Reihe, 1924.",
    "focus": "50% 55%",
    "aspect": 1.384
  },
  {
    "id": "lathe-workshop",
    "licence": "Public domain",
    "licenceUrl": "",
    "artist": "Fortepan — ID 62666: Adományozó/Donor: Veszprém Megyei Levéltár/Klauszer.",
    "page": "https://commons.wikimedia.org/wiki/File%3ALine_shaft%2C_boring_machine%2C_workshop%2C_lathe%2C_belt_drive_Fortepan_62666.jpg",
    "attribution": false,
    "alt": "Werkstatt mit Transmissionsantrieb: eine Welle treibt mehrere Maschinen an.",
    "focus": "50% 45%",
    "aspect": 0.7673
  },
  {
    "id": "micrometer",
    "licence": "CC BY-SA 3.0",
    "licenceUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "artist": "Mauro Cateb",
    "page": "https://commons.wikimedia.org/wiki/File%3A2_Micrometers.JPG",
    "attribution": true,
    "alt": "Zwei Bügelmessschrauben, auf Hundertstel genau ablesbar.",
    "focus": "50% 50%",
    "aspect": 1.3369
  },
  {
    "id": "control-room",
    "licence": "CC BY-SA 4.0",
    "licenceUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "artist": "Consejo General de Educación de Entre Ríos",
    "page": "https://commons.wikimedia.org/wiki/File%3AAprender_(Entre_R%C3%ADos)_-_Tunel_subfluvial_(02).jpg",
    "attribution": true,
    "alt": "Leitstand mit Anzeigen und Schaltern, von dem aus ein Betrieb überwacht wird.",
    "focus": "50% 50%",
    "aspect": 1.4998
  },
  {
    "id": "engine-room",
    "licence": "CC BY 2.0",
    "licenceUrl": "https://creativecommons.org/licenses/by/2.0",
    "artist": "ezioman",
    "page": "https://commons.wikimedia.org/wiki/File%3AMachine_shop%2C_icebreaker_suur_t%C5%8Dll%2C_maritime_museum%2C_tallinn%2C_estonia.jpg",
    "attribution": true,
    "alt": "Maschinenraum eines Eisbrechers: Wellen, Lager und Leitungen ineinander greifend.",
    "focus": "50% 50%",
    "aspect": 1.3333
  },
  {
    "id": "ops-centre",
    "licence": "CC BY-SA 3.0",
    "licenceUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "artist": "RobertHillier1972 at English Wikipedia",
    "page": "https://commons.wikimedia.org/wiki/File%3AADPCentralOps.JPG",
    "attribution": true,
    "alt": "Operations-Zentrale mit Bildschirmreihen und Arbeitsplätzen.",
    "focus": "50% 50%",
    "aspect": 1.5998
  },
  {
    "id": "ledger-book",
    "licence": "Public domain",
    "licenceUrl": "",
    "artist": "Andreas Praefcke",
    "page": "https://commons.wikimedia.org/wiki/File%3AGesch%C3%A4ftsbuch_1833-49_Museum_Senftenberg.jpg",
    "attribution": false,
    "alt": "Aufgeschlagenes Geschäftsbuch von 1833, Spalten von Hand geführt.",
    "focus": "50% 45%",
    "aspect": 1.3432
  }
];

export function photo(id: string): PhotoCredit {
  const found = PHOTO_CREDITS.find((p) => p.id === id);
  if (!found) throw new Error(`Unknown photo id: ${id}`);
  return found;
}
