import type { Metadata } from 'next';
import { PHOTO_CREDITS } from '@/lib/photos';
import { contentPageGraph, jsonLd } from '@/lib/schema';

/**
 * Image credits.
 *
 * Not optional politeness. The photographs come from Wikimedia Commons, and
 * the CC BY / CC BY-SA ones oblige us to name the photographer and the licence
 * wherever the image is shown. Generating this page from src/lib/photos.ts —
 * which is itself generated by scripts/fetch-photos.mjs from the licence the
 * Commons API reported — means adding a photograph cannot quietly skip its
 * credit.
 *
 * CC0 and public-domain images are listed too. They impose no obligation, but
 * saying where a picture came from costs a line and makes the page honest
 * rather than selectively complete.
 */

const TITLE = 'Bildnachweis';
const ROUTE = '/de/bildnachweis/';

export const metadata: Metadata = {
  title: TITLE,
  description:
    'Herkunft und Lizenzen der auf eflury.com verwendeten Fotografien, mit Nennung der Urheber.',
  alternates: { canonical: ROUTE },
};

export default function BildnachweisPage() {
  const needsCredit = PHOTO_CREDITS.filter((p) => p.attribution);
  const free = PHOTO_CREDITS.filter((p) => !p.attribution);

  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: jsonLd(contentPageGraph(ROUTE, TITLE)) }}
      />

      <div className="mx-auto max-w-3xl px-6 pt-16 pb-20">
        <header className="border-b border-[var(--rule-strong)] pb-8">
          <h1 className="display">{TITLE}</h1>
          <p className="mt-5 text-lg leading-relaxed text-[var(--text-muted)]">
            Die Fotografien auf dieser Website stammen von Wikimedia Commons und stehen
            unter freien Lizenzen. Hier stehen Urheber, Lizenz und Quelle jedes Bildes.
          </p>
        </header>

        {needsCredit.length ? (
          <section className="mt-12" aria-labelledby="mit-nennung">
            <h2 id="mit-nennung" className="text-xl font-bold tracking-tight">
              Mit Namensnennung
            </h2>
            <p className="mt-2 text-[0.95rem] leading-relaxed text-[var(--text-muted)]">
              Diese Lizenzen verlangen die Nennung des Urhebers.
            </p>
            <dl className="mt-6 divide-y divide-[var(--rule)]">
              {needsCredit.map((p) => (
                <div key={p.id} className="py-5">
                  <dt className="font-medium">{p.alt}</dt>
                  <dd className="mt-1.5 text-[0.95rem] leading-relaxed text-[var(--text-muted)]">
                    Foto: {p.artist} ·{' '}
                    <a
                      href={p.licenceUrl}
                      rel="license noopener"
                      className="text-[var(--link)] hover:underline"
                    >
                      {p.licence}
                    </a>{' '}
                    ·{' '}
                    <a href={p.page} rel="noopener" className="text-[var(--link)] hover:underline">
                      Quelle auf Wikimedia Commons
                    </a>
                  </dd>
                </div>
              ))}
            </dl>
          </section>
        ) : null}

        {free.length ? (
          <section className="mt-12" aria-labelledby="ohne-nennung">
            <h2 id="ohne-nennung" className="text-xl font-bold tracking-tight">
              Ohne Nennungspflicht
            </h2>
            <p className="mt-2 text-[0.95rem] leading-relaxed text-[var(--text-muted)]">
              CC0 und gemeinfreie Bilder verlangen keine Nennung. Sie steht hier trotzdem.
            </p>
            <dl className="mt-6 divide-y divide-[var(--rule)]">
              {free.map((p) => (
                <div key={p.id} className="py-5">
                  <dt className="font-medium">{p.alt}</dt>
                  <dd className="mt-1.5 text-[0.95rem] leading-relaxed text-[var(--text-muted)]">
                    Foto: {p.artist || 'unbekannt'} · {p.licence} ·{' '}
                    <a href={p.page} rel="noopener" className="text-[var(--link)] hover:underline">
                      Quelle auf Wikimedia Commons
                    </a>
                  </dd>
                </div>
              ))}
            </dl>
          </section>
        ) : null}
      </div>
    </>
  );
}
