#!/usr/bin/env node
/**
 * Downloads the photography in migration/photos.manifest.mjs from Wikimedia
 * Commons, verifies each licence, and writes pre-sized WebP into
 * public/images/photos/ plus a credits module.
 *
 * Pre-sizing is not an optimisation, it is a requirement: the App Hosting
 * adapter rewrites next.config with images.unoptimized = true, so next/image
 * serves whatever file it is given at its original bytes. A 5184px JPEG would
 * ship as a 5184px JPEG.
 *
 * Licences are read from the API at fetch time and checked against ALLOWED. A
 * file that has been re-licensed upstream fails the fetch rather than shipping
 * under a licence we never agreed to. CC BY and CC BY-SA additionally require
 * attribution, which is why credits.ts is generated rather than hand-kept.
 *
 * Run manually after editing the manifest: node scripts/fetch-photos.mjs
 * The output is committed, so a build never depends on Commons being up.
 */
import { mkdir, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import sharp from 'sharp';
import { PHOTOS } from '../migration/photos.manifest.mjs';

const API = 'https://commons.wikimedia.org/w/api.php';
const OUT = join(process.cwd(), 'public/images/photos');
const UA = 'eflury.com image sourcing (https://eflury.com; me@eflury.com)';

/** Licences we accept. Attribution-required ones are flagged, not excluded. */
const ALLOWED = new Map([
  ['CC0', { attribution: false }],
  ['Public domain', { attribution: false }],
  ['CC BY 2.0', { attribution: true }],
  ['CC BY 3.0', { attribution: true }],
  ['CC BY 4.0', { attribution: true }],
  ['CC BY-SA 2.0', { attribution: true }],
  ['CC BY-SA 3.0', { attribution: true }],
  ['CC BY-SA 4.0', { attribution: true }],
]);

/** Commons rate-limits an unthrottled loop; one request at a time, spaced. */
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));

function text(field) {
  if (!field) return '';
  return String(field.value).replace(/<[^>]+>/g, '').replace(/\s+/g, ' ').trim();
}

async function metadata(title) {
  const url = new URL(API);
  url.search = new URLSearchParams({
    action: 'query',
    format: 'json',
    titles: title,
    prop: 'imageinfo',
    iiprop: 'url|size|extmetadata',
    iiextmetadatafilter: 'LicenseShortName|LicenseUrl|Artist|Credit',
  });
  const response = await fetch(url, { headers: { 'user-agent': UA } });
  if (!response.ok) throw new Error(`Commons API ${response.status} for ${title}`);
  const body = await response.json();
  const page = Object.values(body.query?.pages ?? {})[0];
  if (!page || page.missing !== undefined) throw new Error(`Not on Commons: ${title}`);
  const info = page.imageinfo?.[0];
  if (!info) throw new Error(`No imageinfo: ${title}`);
  const meta = info.extmetadata ?? {};
  return {
    source: info.url,
    width: info.width,
    height: info.height,
    licence: text(meta.LicenseShortName),
    licenceUrl: text(meta.LicenseUrl),
    artist: text(meta.Artist),
    page: `https://commons.wikimedia.org/wiki/${encodeURIComponent(title.replace(/ /g, '_'))}`,
  };
}

/*
 * 1600 covers a full-bleed section on a 2x laptop once the CDN has it; 1024 and
 * 640 are the card and mobile cases. Three widths rather than five: every extra
 * one is bytes in the repo for a breakpoint nothing requests.
 */
const WIDTHS = [1600, 1024, 640];

await mkdir(OUT, { recursive: true });
const credits = [];

for (const photo of PHOTOS) {
  const meta = await metadata(photo.title);
  const rule = ALLOWED.get(meta.licence);
  if (!rule) {
    throw new Error(
      `${photo.id}: licence "${meta.licence}" is not in the allow-list (${photo.title})`
    );
  }

  const bytes = Buffer.from(
    await (await fetch(meta.source, { headers: { 'user-agent': UA } })).arrayBuffer()
  );

  for (const width of WIDTHS) {
    if (meta.width < width) continue;
    const out = await sharp(bytes)
      .resize({ width, withoutEnlargement: true })
      .webp({ quality: 78 })
      .toBuffer();
    await writeFile(join(OUT, `${photo.id}-${width}.webp`), out);
  }

  const rendered = await sharp(bytes).metadata();
  credits.push({
    id: photo.id,
    licence: meta.licence,
    licenceUrl: meta.licenceUrl,
    artist: meta.artist,
    page: meta.page,
    attribution: rule.attribution,
    alt: photo.alt,
    focus: photo.focus,
    aspect: Number((rendered.width / rendered.height).toFixed(4)),
  });

  console.log(
    `${photo.id.padEnd(20)} ${meta.licence.padEnd(14)} ${meta.width}x${meta.height} -> ` +
      WIDTHS.filter((w) => meta.width >= w).join(', ')
  );
  await sleep(1200);
}

const creditsModule = `// GENERATED by scripts/fetch-photos.mjs — do not edit by hand.
//
// CC BY and CC BY-SA oblige us to credit the photographer. \`attribution: true\`
// means this image may not be shown without its credit rendered somewhere the
// reader can reach, which is what /de/bildnachweis/ is for.

export interface PhotoCredit {
  id: string;
  licence: string;
  licenceUrl: string;
  artist: string;
  page: string;
  attribution: boolean;
  alt: string;
  focus: string;
  aspect: number;
}

export const PHOTO_CREDITS: PhotoCredit[] = ${JSON.stringify(credits, null, 2)};

export function photo(id: string): PhotoCredit {
  const found = PHOTO_CREDITS.find((p) => p.id === id);
  if (!found) throw new Error(\`Unknown photo id: \${id}\`);
  return found;
}
`;
await writeFile(join(process.cwd(), 'src/lib/photos.ts'), creditsModule);
console.log(`\nwrote src/lib/photos.ts (${credits.length} photos, ${credits.filter((c) => c.attribution).length} needing credit)`);
